[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=86400"
